### ISSUE TITLE
Styleguide reloads on source map change

### ISSUE THREAD

**Issue by mrdziuban** [mpetrovich/stylemark#40]
I'm seeing behavior when using the `-w` flag where the browser reloads twice due to the output CSS file being written, then the source map being written. If I disable source map generation, the browser only reloads once. I've tried using the `match` config option in `.stylemark.yml`, but I can't seem to get it to work. These are the patterns I've tried:

```yaml
match: \.css$
match: "\\.css$"
match: css$
match: "css$"
```

Any idea how I could get this to work? Thanks in advance!
